services:
  mysql:
    image: mysql:8.0
    container_name: digital-subsidy-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: digital_subsidy_grant
      MYSQL_USER: dsgp_user
      MYSQL_PASSWORD: dsgp_password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: