package com.dsgp.beneficiary.entity;

public enum DocumentType {
    IDENTITY_PROOF,
    ADDRESS_PROOF,
    INCOME_CERTIFICATE,
    LAND_RECORD,
    OCCUPATION_PROOF,
    CATEGORY_CERTIFICATE,
    BANK_ACCOUNT_PROOF,
    SCHEME_SPECIFIC_DOCUMENT,
    OTHER_SUPPORTING_DOCUMENT
}